version: "3"
services:
  web:
    image: "codingwombat/vombatidae:master"
    ports:
      - "8081:80"
    environment:
      Cache__UseRedis: "true" 
      Cache__Host: "redis"
      Cache__Instance: "Wombat"
      Cache__SlidingExpiration: 12600
      Cors__Origins__0: "http://example.com" 
      Cors__Origins__1: "https://localhost:8080"
    networks:
      - wombatnet
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - wombatnet
    volumes:
      - redis-data:/data 
networks:
  wombatnet:
volumes:
  redis-data: