#### Burrow

GET  https://localhost:5001/Vombatidae/Burrow
Accept: application/json

> {% client.global.set("guid", response.body.id) %}


#### Burrow docker

GET  http://localhost:8081/Vombatidae/Burrow
Accept: application/json

> {% 
client.global.set("guid", response.body.id)
 %}

#### save history
POST https://localhost:5001/Vombatidae/history/
Accept: application/json

{}

#### get history
GET https://localhost:5001/Vombatidae/history/{{guid}}
Accept: application/json

#### get history docker
GET http://localhost:8081/Vombatidae/history/{{guid}}
Accept: application/json

#### Config
PUT https://localhost:5001/Vombatidae/{{guid}}
Content-Type: application/json

{
  "id": "1c57abf1-8dc2-4a42-8734-e66de66b6e7a",
  "create": "2020-07-21T11:22:47.834561Z",
  "modified": "2020-07-21T11:22:47.834561Z"
}

#### Feeding
PUT https://localhost:5001/Vombatidae/Feed/{{guid}}/foo/bar?method=put
Content-Type: application/json

{
  "StatusCode": 200,
  "ResponseMessage": {
    "String": "this is a test string",
    "int": 123456789,
    "bool": true,
    "datetime":"2020-07-21T11:22:47.834561Z"
  }
}

#### query feed
GET https://localhost:5001/Vombatidae/Feed/{{guid}}/put
Content-Type: application/json


#### Feeding docker
PUT http://localhost:8081/Vombatidae/Feed/{{guid}}/get
Content-Type: application/json

{
  "StatusCode": 200,
  "ResponseMessage": {
    "String": "this is a test string",
    "int": 123456789,
    "bool": true,
    "datetime":"2020-07-21T11:22:47.834561Z"
  }
}

###
POST https://localhost:5001/Vombatidae/{{guid}}
Content-Type: application/json

{
  "foo": "bar"
}

###
GET https://localhost:5001/Vombatidae/{{guid}}
Accept: application/json

### GET docker
GET https://api.codingwombat.dev:5001/Vombatidae/01aee2a3-443f-44ff-a61b-f83fea02ca69?foo=bar&foo=bar2
Accept: application/json


###
PUT https://localhost:5001/Vombatidae/{{guid}}/foo/bar
Content-Type: application/json

{
  "foo": "bar"
}

### 
DELETE https://localhost:5001/Vombatidae/{{guid}}
Content-Type: application/json

{}
