name: .NET Core

on:
  push:
    branches: [ develop, master ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Install version tool
      run: dotnet tool install -g dotnet-setversion
    - name: Call version tool
      run: setversion -r "@version.txt"
    - name: Install dependencies
      run: dotnet restore
    - name: publish
      run: dotnet publish --configuration Release
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        path: /home/runner/work/Vombatidae/Vombatidae/dev.codingWombat.Vombatidae 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: codingwombat/vombatidae
        tags: ${{ steps.extract_branch.outputs.branch }}
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.1.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_USERPASSWORD }}
        DOCKERHUB_REPOSITORY: codingwombat/vombatidae
